/**
 * en.ts — every English word on the site.
 *
 * ar.ts mirrors this file key-for-key (TypeScript enforces it), so when you
 * add or change text here, update ar.ts too.
 * Links are written without the language prefix ("/education"); components
 * add "/ar" for Arabic automatically.
 */
import { STATS, LINKS } from "../site";
import type { Capability, Insight, IrisTopic, Learner, LinkItem, Robot, Stat, Way } from "./types";

const CEO = "Sam";
const CEO_FULL = "Sam Smair";

export const en = {
  // ───────────────────────────────────────────────────────────────────────────
  // Site-wide
  // ───────────────────────────────────────────────────────────────────────────
  meta: {
    title: "Nashmi.bot | Robots that help people with disabilities learn and live independently",
    titleTemplate: "%s | Nashmi.bot",
    description:
      "Nashmi is a family of assistive robots built by DELV Group to help people with disabilities learn, move, communicate and live on their own terms, starting with education.",
    ogTitle: "Nashmi.bot: robots that help people do more",
  },
  brand: {
    name: "Nashmi.bot",
    short: "Nashmi",
    by: "by",
    initiative: "A DELV Group initiative",
    description:
      "Assistive robots that help people with disabilities learn, move, communicate and live independently. Education first. Built in Arabic and English.",
    founded: `DELV Group · founded ${STATS.sinceYear}`,
    copyright: `© ${new Date().getFullYear()} DELV Group. All rights reserved.`,
    builtBy: "Nashmi (نشمي): brave, generous, always there to help.",
  },
  common: {
    skipToContent: "Skip to content",
    langLabel: "عربي",
    langAria: "اقرأ هذه الصفحة بالعربية",
    comingSoon: "Coming soon",
    inProgress: "In progress",
    source: "Source",
    illustrative: "Illustrative example",
    arrow: "→",
    back: "←",
  },
  nav: {
    links: [
      { label: "Home", href: "/" },
      { label: "Nashmi", href: "/nashmi" },
      { label: "Education", href: "/education" },
      { label: "About", href: "/about" },
      { label: "Team", href: "/team" },
      { label: "Insights", href: "/insights" },
      { label: "Contact", href: "/contact" },
    ] as LinkItem[],
    cta: { label: "Join the pilot", href: "/contact?topic=pilot" },
    toggleMenu: "Toggle menu",
  },
  topBanner: {
    live: "Live",
    text: "Building Nashmi in public · robots for independence · education first",
    href: "/news-feed",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Home — Sam's hero, Nashmi focus
  // ───────────────────────────────────────────────────────────────────────────
  hero: {
    eyebrow: "Founder & CEO · DELV Group · Building Nashmi.bot",
    line1: "I didn't wait",
    line2: "for permission.",
    line3: "I just built.",
    body:
      "Everyone keeps asking what I'm building next. Here's the answer: Nashmi. Robots that help people with disabilities learn, move, communicate and live on their own terms, starting in the classroom. Not a slide deck, not a someday. A real build, with an AI team running the operation alongside me. You get a front-row seat to all of it. Every decision, every system, every lesson. Live.",
    socialProof: `${STATS.linkedinFollowers} followers on LinkedIn · Building since ${STATS.sinceYear}`,
    ctaPrimary: { label: "Meet Nashmi →", href: "/nashmi" },
    ctaSecondary: { label: "Follow the journey", href: "/news-feed" },
    stats: [
      { value: STATS.companies, label: "Companies" },
      { value: STATS.people, label: "People" },
      { value: STATS.years, label: "Years" },
      { value: STATS.countries, label: "Countries" },
    ] as Stat[],
    founderTitle: "Founder & CEO",
    irisRole: "Chief of Staff",
    protectedBy: "protected by",
    shielding: "IRIS: shielding",
    pill: "Nashmi.bot in build",
    protectedBadge: "Protected by IRIS",
  },
  marquee: {
    eyebrow: "What Nashmi helps with",
    items: [
      { label: "Education", href: "/education" },
      { label: "Communication", href: "/nashmi#communication" },
      { label: "Mobility", href: "/nashmi#mobility" },
      { label: "Daily living", href: "/nashmi#daily-living" },
      { label: "Therapy & rehab", href: "/nashmi#therapy" },
      { label: "Companionship", href: "/nashmi#companionship" },
    ] as LinkItem[],
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Nashmi — product story (home sections + /nashmi)
  // ───────────────────────────────────────────────────────────────────────────
  nashmi: {
    page: {
      title: "Meet Nashmi",
      eyebrow: "Meet Nashmi",
      heading: "Robots that help people do more.",
      body:
        "Nashmi (نشمي) is the Jordanian word for someone brave and generous, the one who shows up when you need a hand. That's the job we're building our robots for.",
    },
    intro: {
      eyebrow: "Meet Nashmi",
      heading: "A robot that adapts to you, not the other way round.",
      body: [
        "Most technology expects people to fit it. Nashmi starts from the person: how they learn, move, speak and what they want to do on their own.",
        "Each Nashmi robot combines AI that understands Arabic and English with a body built for real help: a face that signs and shows emotion, arms that can point, hand over and guide, and sensors that keep everyone safe.",
      ],
      cta: { label: "See everything Nashmi does →", href: "/nashmi" },
    },
    ways: {
      eyebrow: "More than one way to help",
      heading: "Six ways Nashmi makes life more independent.",
      body: "Disability isn't one thing, so Nashmi isn't one tool. Each robot is configured around the person it supports.",
      items: [
        {
          key: "education",
          icon: "🎓",
          title: "Education",
          body: "A patient, personal tutor in the classroom and at home, teaching at each learner's pace, in the way they learn best.",
          points: ["Reads lessons aloud and converts them to braille", "Live captions and sign language for Deaf learners", "Visual, step-by-step lessons for autistic learners"],
        },
        {
          key: "communication",
          icon: "💬",
          title: "Communication",
          body: "A voice for people who can't speak, and a bridge between sign language, speech and text.",
          points: ["Symbol and eye-gaze talkers (AAC)", "Sign ↔ speech translation", "Speaks for its user in Arabic or English"],
        },
        {
          key: "mobility",
          icon: "🧭",
          title: "Mobility",
          body: "Guidance and a helping hand for getting around school, home, hospital or the street.",
          points: ["Indoor guidance for blind and low-vision users", "Obstacle and step warnings", "Opens doors, calls lifts, carries bags"],
        },
        {
          key: "daily-living",
          icon: "🏠",
          title: "Daily living",
          body: "The small tasks that add up, handled with dignity so people can do more for themselves.",
          points: ["Fetches and hands over objects", "Medication and routine reminders", "Voice control of lights, doors and devices"],
        },
        {
          key: "therapy",
          icon: "💪",
          title: "Therapy & rehab",
          body: "Daily practice between therapist visits, guided, encouraging and measured.",
          points: ["Physiotherapy exercises with real-time feedback", "Speech and language practice games", "Progress shared with the therapist"],
        },
        {
          key: "companionship",
          icon: "🤝",
          title: "Companionship & safety",
          body: "Someone there between visits: conversation, check-ins and help when something goes wrong.",
          points: ["Friendly daily check-ins", "Fall detection and alerts to family", "Calls a carer at the press of a button"],
        },
      ] as Way[],
    },
    education: {
      eyebrow: "Education first",
      heading: "Every child deserves a seat in class, and a way to learn there.",
      body: "Education is where Nashmi starts, because it's where exclusion starts. Nashmi sits beside the learner, not in front of them: it adapts the lesson, keeps the pace and gives the teacher back time for teaching.",
      points: [
        "Personal tutoring at each learner's own pace",
        "Braille, audio, captions, sign language and symbols",
        "Telepresence so homebound students can join class",
        "Progress reports for teachers, parents and therapists",
      ],
      cta: { label: "Explore Nashmi for education →", href: "/education" },
    },
    impact: {
      eyebrow: "Why it matters",
      heading: "The need is real, and it's huge.",
      stats: [
        { value: "1 in 6", label: "people worldwide live with a significant disability (about 1.3 billion).", source: "WHO", href: LINKS.whoDisability },
        { value: "240M", label: "children around the world live with disabilities.", source: "UNICEF", href: LINKS.unicefChildren },
        { value: "49%", label: "more likely: children with disabilities who have never attended school.", source: "UNICEF", href: LINKS.unicefChildren },
        { value: "42%", label: "less likely to have foundational reading and numeracy skills.", source: "UNICEF", href: LINKS.unicefChildren },
      ],
    },
    how: {
      eyebrow: "How Nashmi works",
      heading: "People first. Robot second.",
      steps: [
        { title: "Listen", body: "We start with the person, their family, teachers and therapists: abilities, goals, language and what a good day looks like." },
        { title: "Personalise", body: "Nashmi is configured around one person: how it speaks, signs, moves and which tasks it helps with." },
        { title: "Support", body: "The robot works alongside them every day at school, at home or in therapy, with an app for family and staff." },
        { title: "Learn & improve", body: "Progress is shared with the people who matter, and humans decide what changes next." },
      ],
    },
    principles: {
      eyebrow: "Our principles",
      heading: "Built with people with disabilities, not just for them.",
      items: [
        { title: "Dignity first", body: "Nashmi helps people do things themselves. It never takes over, talks down or decides for them." },
        { title: "Humans stay in charge", body: "Teachers, therapists, families and users make the decisions. Nashmi supports them." },
        { title: "Private by design", body: "Personal data stays protected, shared only with the people the user chooses." },
        { title: "Arabic-first, open to all", body: "Built to understand Arabic dialects and Arabic sign language, as well as English." },
        { title: "Safe around people", body: "Soft materials, gentle force limits and constant awareness of who's nearby." },
        { title: "Affordable access", body: "Designed for schools, clinics and families, not only for those who can pay the most." },
      ],
    },
    robots: {
      eyebrow: "The Nashmi family",
      heading: "Three robots. One mission.",
      body: "Each Nashmi is built for a different part of life, and they all share the same AI, the same app and the same principles.",
      items: [
        {
          name: "Nashmi Tutor",
          role: "Classroom & home learning",
          status: "Pilot program",
          body: "A friendly desktop robot with an expressive screen face and two arms. It tutors, signs, reads aloud and keeps learners on track.",
          features: ["Arabic & English tutoring", "Signing arms and face", "Braille display connection", "Teacher dashboard"],
        },
        {
          name: "Nashmi Guide",
          role: "Mobility & independence",
          status: "In development",
          body: "A wheeled guide that leads the way, warns of obstacles and steps, carries what its user needs and calls lifts.",
          features: ["Indoor navigation", "Obstacle & step alerts", "Carries up to a school bag", "Voice and haptic handle"],
        },
        {
          name: "Nashmi Home",
          role: "Daily living & companionship",
          status: "In development",
          body: "A gentle robotic arm on a mobile base that fetches, hands over, reminds and keeps family in the loop.",
          features: ["Fetch & hand-over", "Routine reminders", "Fall detection & alerts", "Smart-home control"],
        },
      ] as Robot[],
    },
    faq: {
      eyebrow: "Questions",
      heading: "What people ask us.",
      items: [
        { q: "Is Nashmi available today?", a: "Nashmi Tutor is entering a pilot program with schools and families. Nashmi Guide and Nashmi Home are in development. Join the pilot to be among the first." },
        { q: "Does Nashmi replace teachers, therapists or carers?", a: "No. Nashmi supports the people who already help. They stay in charge and decide what it does." },
        { q: "Which languages does Nashmi speak?", a: "Arabic (including local dialects) and English, with Arabic and international sign language support in development." },
        { q: "What about privacy?", a: "Data belongs to the user and their family. Nothing is shared without permission, and schools control their own classroom data." },
        { q: "Who builds Nashmi?", a: `Nashmi is built by DELV Group, a technology company with ${STATS.years} years of experience in AI, platforms and robotics, led by founder & CEO ${CEO_FULL}.` },
      ],
    },
    pilot: {
      heading: "Help us build Nashmi.",
      body: "We're looking for schools, clinics, families and partners to shape Nashmi with us. Tell us who you are and how you'd like to be involved.",
      cta: { label: "Join the pilot →", href: "/contact?topic=pilot" },
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Education page
  // ───────────────────────────────────────────────────────────────────────────
  education: {
    page: {
      title: "Education",
      eyebrow: "Nashmi for education",
      heading: "A classroom where every learner belongs.",
      body: "Nashmi Tutor gives each student a patient, personal learning partner, and gives teachers the tools to include everyone in the same lesson.",
    },
    learnersEyebrow: "Every learner, their own way",
    learnersHeading: "One lesson. Many ways in.",
    learners: [
      {
        key: "blind",
        icon: "👁️",
        title: "Blind & low vision",
        who: "Students who learn by listening and touch",
        body: "Nashmi reads textbooks and the board aloud, describes images and diagrams, and sends lessons to a braille display.",
        tools: ["Text-to-speech in Arabic & English", "Image and diagram descriptions", "Braille display output", "Spoken navigation of worksheets"],
      },
      {
        key: "deaf",
        icon: "🤟",
        title: "Deaf & hard of hearing",
        who: "Students who learn visually",
        body: "Live captions of everything the teacher says, sign language through Nashmi's face and arms, and visual alerts instead of sounds.",
        tools: ["Live classroom captions", "Sign language explanations", "Visual cues and alerts", "Recorded, captioned lesson replays"],
      },
      {
        key: "autism",
        icon: "🧩",
        title: "Autism & learning differences",
        who: "Including dyslexia and ADHD",
        body: "A calm, predictable partner that breaks work into steps, repeats without judgement and practises social skills safely.",
        tools: ["Visual schedules and step-by-step tasks", "Dyslexia-friendly reading support", "Focus timers and gentle prompts", "Social-skills practice games"],
      },
      {
        key: "physical",
        icon: "♿",
        title: "Physical disabilities",
        who: "Students with limited movement",
        body: "Hands-free learning by voice, switch or eye gaze. Nashmi turns pages, operates the tablet and hands over materials.",
        tools: ["Voice, switch and eye-gaze control", "Page turning and hand-over", "Accessible quizzes and tests", "Works with wheelchair setups"],
      },
      {
        key: "speech",
        icon: "🗣️",
        title: "Speech & communication",
        who: "Students who are non-verbal or developing speech",
        body: "Symbol boards and a synthetic voice let students answer, ask and join in, while speech practice happens through play.",
        tools: ["Symbol-based communication (AAC)", "Answer aloud in class", "Speech practice games", "Personal voice options"],
      },
      {
        key: "homebound",
        icon: "🏥",
        title: "Homebound & hospitalised",
        who: "Students who can't be in class",
        body: "A Nashmi in the classroom becomes their eyes, ears and voice, so they can see the board, raise a hand and stay with their friends.",
        tools: ["Telepresence in class", "Raise hand and speak remotely", "Shared lesson materials", "Stay connected with classmates"],
      },
    ] as Learner[],
    day: {
      eyebrow: "A day with Nashmi",
      heading: "What a school day can look like.",
      note: "Illustrative example of Nashmi Tutor in an inclusive classroom.",
      items: [
        { time: "7:45", title: "Good morning, Layla", body: "Nashmi greets Layla by name, shows her visual schedule for the day and checks how she's feeling." },
        { time: "8:30", title: "Arabic reading", body: "The teacher reads to the class. Nashmi captions it live for Omar, who is Deaf, and sends the text to Sara's braille display." },
        { time: "10:00", title: "Maths, at your pace", body: "Each student works on the same topic at their own level. Nashmi gives hints, never answers, and tells the teacher who's stuck." },
        { time: "11:30", title: "Yousef joins from hospital", body: "Through the classroom Nashmi, Yousef sees the board, raises his hand and presents his science project." },
        { time: "13:00", title: "Break-time skills", body: "Nashmi practises taking turns and starting conversations with students who want a little support." },
        { time: "14:30", title: "Report home", body: "Parents and the therapist get a short summary: what was learned, what was hard, what's next." },
      ],
    },
    featuresEyebrow: "For teachers & schools",
    featuresHeading: "More time for teaching. Nobody left behind.",
    features: [
      { title: "Adaptive lessons", body: "Content adjusts to each learner's level and preferred format, without the teacher making five versions." },
      { title: "Progress at a glance", body: "A simple dashboard shows each student's progress and individual education plan goals." },
      { title: "Curriculum-friendly", body: "Teachers load their own lessons and materials. Nashmi adapts them, it doesn't replace them." },
      { title: "Arabic-first", body: "Built for Arabic classrooms and dialects, with English for bilingual schools." },
      { title: "Safe & private", body: "Student data stays with the school and family, protected and never sold." },
      { title: "Training included", body: "Teachers and parents learn to use Nashmi through Akademija, our practical training program." },
    ],
    programsEyebrow: "Get involved",
    programsHeading: "Three ways to bring Nashmi to learners.",
    programs: [
      { title: "School pilot", body: "Bring Nashmi Tutor into an inclusive classroom for a term, with setup, training and support.", cta: { label: "Apply for the school pilot →", href: "/contact?topic=school" } },
      { title: "Home learning", body: "Nashmi Tutor at home for homework, therapy practice and reading, connected to the child's school.", cta: { label: "Register your family →", href: "/contact?topic=family" } },
      { title: "Teacher training", body: "Practical courses on assistive technology and AI in the classroom, through Akademija.", cta: { label: "Explore Akademija →", href: "/akademija" } },
    ],
    cta: {
      heading: "Let's make your classroom accessible.",
      body: "Whether you're a teacher, a principal, a parent or a ministry, we'd love to hear what your learners need.",
      label: "Talk to the Nashmi team →",
      href: "/contact?topic=school",
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Home sections kept from the original site
  // ───────────────────────────────────────────────────────────────────────────
  liveLog: {
    eyebrow: "Live Log",
    heading: "Building Nashmi in public.",
    subheading: "A real-time record of wins, fails and lessons from building robots that help people. Unfiltered.",
    monitorTitle: "nashmi://build monitor",
    liveLabel: "LIVE",
    initState: "Initializing...",
    initSubstate: "0 agents active · 0 robots online",
    lastUpdate: "last update: 0 seconds ago",
    liveState: `${STATS.agentsTotal} agents active · Nashmi Tutor pilot prep · 0 errors`,
    cta: { label: "Enter the Log →", href: "/news-feed" },
  },
  team: {
    eyebrow: "The Team",
    heading: "I didn't build this alone.",
    body: "Alongside the DELV team, I run a team of AI agents: each one built for a specific job, trained on how I think, and running 24/7 while we build Nashmi. This is how a small team builds what should take fifty.",
    cta: { label: "Meet the team →", href: "/team" },
    summaryHeading: `${STATS.agentsTotal} AI agents. ${STATS.osPlatforms} OS platforms. Running 24/7.`,
    summaryBody: `${STATS.agentsDirect} direct agents (IRIS, AXIS, REEL, VOICE, NOVA, COPY, Aria, Spark, Rex) + 15 OS agents across buildOS (7 dev agents), ProductionOS (VEGA, QUILL, LENS, INK), and SOVP (PULSE, REMIX, GATE, HYPE). All led by IRIS: Chief of Staff.`,
    stats: [
      { value: STATS.agentsTotal, label: "Agents" },
      { value: STATS.osPlatforms, label: "OS" },
      { value: "24/7", label: "Online" },
      { value: "1", label: "Chief of Staff" },
    ] as Stat[],
    agents: [
      { initial: "I", name: "IRIS", role: "Chief of Staff" },
      { initial: "A", name: "AXIS", role: "Content Writer" },
      { initial: "R", name: "REEL", role: "Video Producer" },
      { initial: "V", name: "VOICE", role: "Audio & Voice" },
      { initial: "N", name: "NOVA", role: "Visual Identity" },
      { initial: "C", name: "COPY", role: "Copywriter" },
    ],
    moreAgentsBadge: "+18",
    roster: [
      {
        group: "Direct agents",
        note: "",
        agents: [
          { name: "IRIS", role: "Chief of Staff" },
          { name: "AXIS", role: "Content Writer" },
          { name: "REEL", role: "Video Producer" },
          { name: "VOICE", role: "Audio & Voice" },
          { name: "NOVA", role: "Visual Identity" },
          { name: "COPY", role: "Copywriter" },
          { name: "Aria", role: "" },
          { name: "Spark", role: "" },
          { name: "Rex", role: "" },
        ],
      },
      { group: "buildOS", note: "7 dev agents", agents: [] as { name: string; role: string }[] },
      { group: "ProductionOS", note: "", agents: [{ name: "VEGA", role: "" }, { name: "QUILL", role: "" }, { name: "LENS", role: "" }, { name: "INK", role: "" }] },
      { group: "SOVP", note: "", agents: [{ name: "PULSE", role: "" }, { name: "REMIX", role: "" }, { name: "GATE", role: "" }, { name: "HYPE", role: "" }] },
    ],
    agentsLabel: "agents",
    roleTbd: "Role coming soon",
  },
  protocol: {
    eyebrow: "How it works",
    heading: "The IRIS Protocol",
    subheading: `The relationship between ${CEO} and IRIS: how autonomous AI coordinates ${STATS.companies} companies and the Nashmi build while keeping humans in control of what matters.`,
    iris: {
      role: "Chief of Staff",
      name: "IRIS",
      typeLabel: "((AI))",
      points: [
        `Communicates directly with ${CEO}`,
        "Autonomous, develops herself",
        "Talks to everyone in the company",
        "Sets tasks & coordinates all teams",
        `Creates tasks for ${CEO} when blocked`,
        `Thinks identically to ${CEO}`,
      ],
      footnote: "24/7 operational. No days off. Learns from every decision.",
    },
    founder: {
      role: "Founder",
      name: CEO,
      typeLabel: "((Human))",
      points: ["Sets vision & strategy", "Receives optimizations from IRIS", "Approves critical decisions", "Handles key relationships", "Available for qualified contacts", "Guides the ecosystem"],
      footnote: "Focused on Nashmi, strategy & key people.",
    },
    pillars: [
      { icon: "💬", title: "Slack & Direct Talk", bullets: ["Connected to **every company** via Slack", "Monitors all channels **24/7**", `Direct line to ${CEO} via **DM & task queue**`, "Creates tasks automatically when issues arise"], footer: "Always listening" },
      { icon: "🎯", title: "Problem Detection", bullets: ["Spots **revenue drops** before they escalate", "Flags **anomalies** in real-time", "Identifies **hotspots** across all companies", "Reports with context and **recommended fixes**"], footer: "Active monitoring" },
      { icon: "↻", title: "Optimization Loop", bullets: [`Suggests **optimizations** to ${CEO}`, "When blocked, creates **tasks for approval**", `${CEO} provides **strategic direction**`, "System adapts & **continues autonomously**"], footer: "Continuous improvement" },
    ],
    connectionMap: {
      title: "Live Connection Map",
      hubLabel: "IRIS",
      spokes: ["Nashmi.bot", "Platform Development", "AI Services", "Robotics", "Advisory"],
      caption: `All communication and task creation flows through IRIS. Problems are identified, optimizations are suggested, and ${CEO} stays in control through a single command center.`,
    },
  },
  presence: {
    eyebrow: "Presence",
    heading: "The Ecosystem",
    body: `${STATS.companies} companies. ${STATS.countries} countries. Built from the ground up. Operating globally across Europe, North America, Middle East, and Southeast Asia.`,
    legend: { office: "Office", remote: "Remote / Partners" },
    stats: [
      { value: STATS.countries, label: "Countries" },
      { value: STATS.cities, label: "Cities" },
      { value: STATS.companies, label: "Companies" },
      { value: STATS.continents, label: "Continents" },
    ] as Stat[],
    footnote: `Building since ${STATS.sinceYear} · ${STATS.countries} countries · ${STATS.people} people impacted`,
  },
  akademija: {
    title: "Akademija",
    eyebrow: "Early Access",
    heading: "Akademija",
    body1:
      "AI and robots are changing how people learn and work, and that includes people with disabilities and everyone who supports them. Akademija teaches teachers, parents, carers and anyone curious how to use AI and assistive technology in real life.",
    body2: "No theory, no jargon. Practical lessons you can use the same day, in Arabic and English.",
    pillars: [
      { icon: "🍎", title: "For teachers", body: "Make your classroom accessible: adapt lessons, use assistive tools and work alongside Nashmi." },
      { icon: "👪", title: "For families", body: "Support learning and independence at home with the right apps, devices and routines." },
      { icon: "🤖", title: "Practical AI skills", body: "Emails, reports, planning, research. Let AI handle the repetitive work so you can focus on people." },
      { icon: "🎯", title: "Stay ahead", body: "Those who learn AI and assistive technology now will shape how it's used tomorrow." },
    ],
    cta: { label: "Join Akademija →", href: "/akademija" },
    ctaNote: "Get notified when enrollment opens",
  },
  newsletter: {
    title: "Newsletter",
    eyebrow: "Every Friday",
    heading: "Live Log Weekly",
    body: "One email per week. What we're building at Nashmi, what's working, what's not. No fluff.",
    bullets: ["What shipped this week", "Honest breakdowns of what didn't work", "Stories from the classrooms and families we work with"],
    inputPlaceholder: "you@email.com",
    inputLabel: "Email address",
    submitLabel: "Subscribe Free",
    microcopy: "Join the people following the build. Unsubscribe anytime.",
  },
  founder: {
    eyebrow: "About",
    heading: "Built from nothing.",
    headingHighlight: "Owned from day one.",
    paragraphs: [
      `For ${STATS.years} years, I've built companies at the intersection of technology, performance marketing and business scaling: a network of ${STATS.companies} companies with ${STATS.people} people across ${STATS.countries} countries.`,
      "No VC funding, no Silicon Valley network. Just a clear view of how technology works when you treat it as ownership, not a cost.",
      "Nashmi is the most important thing I've built. Robots that give people with disabilities more independence, starting with the right to learn. I'm building it in public, with the DELV team and an AI team of 24 agents beside me.",
    ],
    attribution: `- ${CEO_FULL}, Founder & CEO`,
    location: "Founder & CEO · DELV Group",
    quote: "Technology should give people more independence, not more things to depend on.",
  },
  footer: {
    columns: [
      {
        heading: "Nashmi",
        links: [
          { label: "Meet Nashmi", href: "/nashmi" },
          { label: "Education", href: "/education" },
          { label: "Join the pilot", href: "/contact?topic=pilot" },
          { label: "Akademija", href: "/akademija" },
          { label: "Live Log", href: "/news-feed" },
          { label: "Newsletter", href: "/newsletter" },
        ],
      },
      {
        heading: "DELV Group",
        links: [
          { label: "About", href: "/about" },
          { label: "Team", href: "/team" },
          { label: "Services", href: "/services" },
          { label: "Robotics", href: "/services/robotics" },
          { label: "Insights", href: "/insights" },
          { label: "Contact", href: "/contact" },
        ],
      },
    ] as { heading: string; links: LinkItem[] }[],
    newsletterTeaser: "Live Log Weekly: wins, fails & lessons. Every Friday.",
    newsletterCta: "Subscribe",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // IRIS chat
  // ───────────────────────────────────────────────────────────────────────────
  iris: {
    name: "IRIS",
    badge: "AI",
    role: "Chief of Staff",
    tagline: `I handle everything so ${CEO} can focus on building Nashmi. Ask me anything.`,
    chatPrompt: "Chat with me",
    inputPlaceholder: "Type a message...",
    sendLabel: "Send",
    closeLabel: "Close chat",
    openLabel: "Open IRIS chat",
    dialogLabel: "IRIS chat",
    greeting: `Hey! I'm IRIS, ${CEO}'s Chief of Staff. Ask me about Nashmi, how it helps in the classroom, or how to get involved.`,
    thinkingLabel: "IRIS is thinking…",
    suggestionsLabel: "Try asking",
    suggestions: ["What is Nashmi?", "How does Nashmi help in school?", "Can my school join the pilot?", "Who is building Nashmi?"],
    topics: [
      { keywords: ["school", "class", "teach", "student", "learn", "education", "lesson"], answer: "Education is where Nashmi starts. Nashmi Tutor reads aloud and sends lessons to braille, captions and signs for Deaf learners, breaks work into steps for autistic learners, and lets homebound students join class by telepresence.", link: { label: "Nashmi for education", href: "/education" } },
      { keywords: ["pilot", "join", "apply", "available", "buy", "price", "cost"], answer: "Nashmi Tutor is entering a pilot program with schools, clinics and families. Tell us about you and we'll be in touch within one business day.", link: { label: "Join the pilot", href: "/contact?topic=pilot" } },
      { keywords: ["blind", "vision", "see", "braille"], answer: "For blind and low-vision users, Nashmi reads text and the board aloud, describes images, connects to braille displays, and Nashmi Guide helps with indoor navigation and obstacle warnings.", link: { label: "Learn more", href: "/education" } },
      { keywords: ["deaf", "hearing", "sign", "caption"], answer: "Nashmi captions speech live, explains in sign language through its face and arms, and uses visual alerts instead of sounds. Arabic and international sign language support is in development.", link: { label: "Learn more", href: "/education" } },
      { keywords: ["autis", "adhd", "dyslex"], answer: "Nashmi is a calm, predictable partner: visual schedules, step-by-step tasks, focus support and safe social-skills practice, at the learner's own pace.", link: { label: "Learn more", href: "/education" } },
      { keywords: ["wheelchair", "mobility", "move", "walk", "guide"], answer: "Nashmi Guide leads the way indoors, warns about obstacles and steps, carries a bag and calls lifts. Nashmi Home fetches and hands over objects.", link: { label: "Meet the robots", href: "/nashmi" } },
      { keywords: ["speak", "talk", "voice", "aac", "communicat"], answer: "Nashmi gives a voice to people who can't speak, with symbol and eye-gaze communication, and translates between sign, speech and text in Arabic and English.", link: { label: "Meet Nashmi", href: "/nashmi#communication" } },
      { keywords: ["therapy", "rehab", "physio", "exercise"], answer: "Between therapist visits, Nashmi guides exercises and speech practice with real-time feedback, and shares progress with the therapist.", link: { label: "Meet Nashmi", href: "/nashmi#therapy" } },
      { keywords: ["privacy", "data", "safe"], answer: "Data belongs to the user and their family. Nothing is shared without permission, and the robots are designed with gentle force limits and constant awareness of people nearby.", link: { label: "Our principles", href: "/nashmi" } },
      { keywords: ["arabic", "language", "english", "عربي"], answer: "Nashmi is Arabic-first: it understands Arabic dialects and English, and this site works in both. Tap عربي at the top.", link: { label: "Meet Nashmi", href: "/nashmi" } },
      { keywords: ["nashmi", "robot", "what is", "what does"], answer: "Nashmi is a family of assistive robots (Tutor, Guide and Home) that help people with disabilities learn, communicate, move and live independently. Education comes first.", link: { label: "Meet Nashmi", href: "/nashmi" } },
      { keywords: ["sam", "founder", "ceo", "who", "delv", "build"], answer: `Nashmi is built by DELV Group, founded in ${STATS.sinceYear}, and led by ${CEO_FULL}, Founder & CEO. I'm IRIS, the AI Chief of Staff on his team.`, link: { label: "About", href: "/about" } },
      { keywords: ["akademija", "course", "training"], answer: "Akademija teaches teachers, parents and carers practical AI and assistive technology, in Arabic and English. Enrollment opens soon.", link: { label: "Akademija", href: "/akademija" } },
      { keywords: ["contact", "email", "call", "reach", "partner", "fund", "invest"], answer: "The fastest route is the contact form: a senior team member replies within one business day.", link: { label: "Contact", href: "/contact" } },
    ] as IrisTopic[],
    cannedResponses: [
      "Good question. The team can give you a precise answer. Want me to point you to the contact form?",
      "Nashmi helps with education, communication, mobility, daily living, therapy and companionship. Ask me about any of them.",
      "IRIS here. I can tell you about Nashmi, how it works in the classroom, or how to join the pilot. What are you working on?",
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Inner pages
  // ───────────────────────────────────────────────────────────────────────────
  pages: {
    about: {
      title: "About",
      eyebrow: "About",
      heading: "Why we're building Nashmi.",
      body: "Nashmi is a DELV Group initiative, led by founder & CEO Sam Smair, to make independence easier for people with disabilities, starting with education.",
      missionEyebrow: "Our mission",
      missionHeading: "Independence, learning and dignity for everyone.",
      mission: [
        "One in six people lives with a significant disability. Too many of them are still left out of classrooms, jobs and everyday life, not because of what they can't do, but because the world wasn't built for them.",
        "Nashmi puts capable, patient robots beside people to close that gap: helping them learn, communicate, move and do more on their own terms.",
      ],
      groupEyebrow: "Built by DELV Group",
      groupHeading: "Twenty years of technology that has to work.",
    },
    team: {
      title: "Team",
      eyebrow: "The Team",
      heading: "Meet the agents.",
      body: `${STATS.agentsTotal} AI agents across ${STATS.osPlatforms} OS platforms, all coordinated by IRIS, working alongside the DELV team to build Nashmi.`,
    },
    services: {
      title: "Services",
      eyebrow: "DELV Group services",
      heading: "The company behind Nashmi.",
      body: "DELV Group delivers platforms, AI, robotics and advisory end to end, from the first prototype to managed operations. The same capability builds Nashmi.",
      capabilitiesEyebrow: "Four pillars",
      capabilitiesHeading: "Engage one service, or the whole journey.",
      capabilitiesBody: "Each pillar can be engaged on its own, or as part of an end-to-end program.",
      offersEyebrow: "Entry-point offers",
      offersHeading: "Structured engagements designed for clarity.",
      offersBody: "Each offer is time-boxed, deliverable-driven and designed to inform a bigger decision.",
      industriesEyebrow: "Industries",
      industriesHeading: "We've worked in your environment before.",
      industriesBody: "Government, enterprise, regulated sectors. We understand the constraints (procurement, security, compliance) and we deliver within them.",
      exploreLabel: "Explore →",
      offerLabel: "Offer",
      sectorLabel: "Sector",
      backLabel: "← All services",
      howWeWork: "How we work",
      processHeading: "How an engagement works.",
      ctaHeading: "Start somewhere. We'll take you the rest of the way.",
      ctaBody: "Engage one service or the full lifecycle. DELV scales to where you are and where you need to get to.",
      ctaLabel: "Contact us →",
      startHere: "Sound familiar?",
      ctaHref: "/contact",
    },
    insights: {
      title: "Insights",
      eyebrow: "Insights",
      heading: "Notes from the build.",
      body: "Assistive robotics, accessible education, AI governance and the lessons from building Nashmi.",
      allTopics: "All topics",
      featuredLabel: "Featured",
      filterLabel: "Filter by topic",
      footerHeading: "The thinking and the doing are the same team.",
      footerBody: "Every piece of thinking here is backed by real delivery. Get new articles first in Live Log Weekly.",
    },
    newsFeed: {
      title: "Live Log",
      buildEyebrow: "Nashmi build log",
      buildHeading: "Where the build is now.",
      build: [
        { era: "Now", title: "Nashmi Tutor pilot preparation", body: "Preparing the first classroom pilots: Arabic reading support, live captions and the teacher dashboard." },
        { era: "Next", title: "Signing arms and face", body: "Teaching Nashmi to explain in sign language, with Deaf educators reviewing every sign." },
        { era: "Then", title: "Nashmi Guide and Nashmi Home", body: "Indoor navigation and fetch-and-carry prototypes for mobility and daily living." },
      ],
      archiveEyebrow: "Where we come from",
      archiveHeading: "DELV Group, one chapter at a time.",
      archiveBody: "Twenty years of technology delivery. Each capability now powers Nashmi.",
      emptyHeading: "Live entries are coming.",
      emptyBody: "Every win, fail and lesson from the Nashmi build will be posted here as it happens.",
    },
    contact: {
      title: "Contact",
      eyebrow: "Get in touch",
      heading: "Let's build Nashmi together.",
      body: "Schools, families, clinics, partners and funders: tell us who you are. A senior team member responds within one business day.",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      organisation: "School / organisation (optional)",
      topic: "How would you like to be involved?",
      topicPlaceholder: "Select an option",
      message: "Tell us about you and your needs",
      submit: "Send message →",
      sentHeading: "Your email app should now be open.",
      sentBody: "Send the drafted email and we'll be in touch within one business day. Nothing opened? Email us directly:",
      directHeading: "Prefer email?",
      founderLabel: "Founder & CEO",
      companyLabel: "DELV Group",
      location: "Canberra, Australia",
      subjectPrefix: "Nashmi enquiry",
      topics: [
        { value: "pilot", label: "Join the Nashmi pilot" },
        { value: "school", label: "Nashmi for my school" },
        { value: "family", label: "Nashmi for my family" },
        { value: "clinic", label: "Clinic or therapy centre" },
        { value: "partner", label: "Partnership or funding" },
        { value: "akademija", label: "Akademija training" },
        { value: "delv", label: "DELV Group services" },
        { value: "general", label: "General enquiry" },
      ],
    },
    notFound: {
      title: "Page not found",
      eyebrow: "404",
      heading: "Nothing here yet.",
      body: "This page doesn't exist, or it hasn't been built yet.",
      cta: { label: "Back to home", href: "/" },
    },
    comingSoonCta: { label: "Subscribe to Live Log Weekly →", href: "/newsletter" },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // DELV Group (the company behind Nashmi)
  // ───────────────────────────────────────────────────────────────────────────
  delv: {
    name: "DELV Group",
    location: "Canberra, Australia",
    tagline: "Advisory · Development · Deployment · Managed Operations",
    summary:
      "DELV helps organisations turn AI, software and robotics into secure, governed capability, from strategy and prototyping through deployment and ongoing operation.",
    credentials: [
      { label: "Founded", value: "2006" },
      { label: "Sectors", value: "Government & Enterprise" },
      { label: "Recognition", value: "BRW Fast 100" },
      { label: "Approach", value: "Human-centred technology" },
      { label: "Heritage", value: "Automation, IoT & intelligent systems" },
      { label: "Delivery", value: "Secure digital delivery" },
    ],
    experience: [
      { value: "20+", label: "Years in operation" },
      { value: "BRW", label: "Fast 100 recognition" },
      { value: "Gov", label: "Federal & state clients" },
      { value: "End-to-end", label: "Strategy to operation" },
    ] as Stat[],
    purpose: {
      eyebrow: "Our purpose",
      heading: "Making technology more human.",
      body: [
        "DELV exists to connect people through technology, turning complex ideas into systems that deliver real outcomes.",
        "We design technology around the people who use it, manage it and trust it. Nashmi is that principle taken to its most personal place.",
      ],
    },
    story: {
      eyebrow: "DELV Group",
      heading: "A technology company built for change.",
      body: "For twenty years, DELV has helped government and enterprise organisations build, deploy and manage technology in environments where it genuinely has to work: securely, at scale, with no room for experiments that go nowhere.",
    },
    heritage: [
      { eyebrow: "Heritage", title: "Enterprise Mobility Pioneer", body: "DELV began as one of Australia's leading enterprise mobility and MDM/EMM/UEM specialists, managing thousands of devices for government and enterprise clients." },
      { eyebrow: "Recognition", title: "BRW Fast 100", body: "Recognised as one of Australia's fastest-growing technology companies. A track record of delivery, not just ambition." },
      { eyebrow: "Evolution", title: "From Managed Services to AI", body: "From BlackBerry and device management to platforms, AI, robotics and now Nashmi. DELV keeps evolving to stay at the frontier." },
    ],
    whyDelv: [
      { title: "Strategy first", body: "We identify where AI genuinely creates value, and where it does not. No wasted investment." },
      { title: "We build what we advise", body: "Our advisory team and engineering team are the same team. Strategy leads directly to execution." },
      { title: "Human-centred AI", body: "AI designed around the people who use it. Adoption requires simplicity; we engineer for it from day one." },
      { title: "Governed by design", body: "AI governance, security and policy are built in from the start, not bolted on after the fact." },
      { title: "End-to-end delivery", body: "We advise, design, build, deploy and operate. One partner across the full journey." },
      { title: "20 years of delivery trust", body: "Two decades of government and enterprise delivery. We know what breaks at scale and build to prevent it." },
    ],
    values: [
      { title: "Customer first", body: "Every decision starts with what creates the most value for the people we serve." },
      { title: "Act with integrity", body: "Honest about what we can deliver. If something will not work, we say so." },
      { title: "Think big, move fast", body: "Strategic ambition combined with operational practicality." },
      { title: "Be different", body: "We explore emerging technology early, test what is practical, and help people adopt it when it is ready." },
    ],
    labels: {
      talk: "Talk to us →",
      servicesCta: "DELV Group services",
      heritageEyebrow: "Our experience",
      heritageHeading: "Twenty years of technology delivery.",
      heritageBody: "Our foundation in enterprise mobility, security and managed services gives DELV the credibility to deploy AI and robots where they genuinely have to work, including with the people Nashmi serves.",
      valuesEyebrow: "How we work",
      valuesHeading: "Four principles. No exceptions.",
      contact: "Contact us →",
      evolutionEyebrow: "Evolution",
      evolutionHeading: "Continuity, not reinvention.",
      whyEyebrow: "Why DELV",
      whyHeading: "Experience that reduces risk.",
      valueLabel: "Value",
      visitSite: "Visit delv.group ↗",
    },
    future: {
      heading: "The next capability is already in motion.",
      body: "As robotics moves from factories into schools, homes and hospitals, DELV is building Nashmi to make sure it arrives for the people who need it most.",
    },
    timeline: [
      { era: "Origin · 2006", title: "Government IT", body: "Founded in Canberra in 2006 on government and enterprise IT. BRW Fast 100 recognised. Human-centred technology as a principle from day one." },
      { era: "Mobility", title: "Mobility & Managed Endpoints", body: "Enterprise mobility and secure managed environments, shifting the focus from devices to people." },
      { era: "Connected", title: "IoT / Intelligent Things", body: "Sensors, connectivity and automation: intelligent environments before AIoT became common language." },
      { era: "Automation", title: "Intelligent Automation", body: "Digital workers and human-in-the-loop process design, the foundation for modern AI agents." },
      { era: "Intelligence", title: "AI Services", body: "Strategy, governance, private AI, agents, RAG, deployment and managed AI operations." },
      { era: "Today", title: "Robotics & Nashmi", body: "Humanoid, quadruped and wheeled platforms, and now Nashmi: robots that help people with disabilities." },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  // DELV services (/services)
  // ───────────────────────────────────────────────────────────────────────────
  capabilities: [
    {
      slug: "platform-development",
      number: "01",
      name: "Platform Development",
      short: "Apps, SaaS platforms, internal tools and customer portals: increasingly AI-enabled, always built for real-world use.",
      intro: "Strategy, design, engineering and managed operations, one team across the full lifecycle.",
      prompts: ["An idea to validate before building?", "Inherited a platform that underperforms?", "Need an MVP that scales into a real product?"],
      groups: [
        {
          title: "What we build",
          summary: "From idea to managed platform.",
          items: ["Mobile applications", "Web applications", "SaaS platforms", "Startup MVPs", "Enterprise systems", "Internal business tools", "Customer portals", "Workflow platforms", "AI-enabled software", "Integrations and APIs", "Cloud platforms", "Managed product support"],
        },
      ],
      highlight: { eyebrow: "AI app development", title: "Intelligent applications. Built for real use.", body: "From MVPs to enterprise platforms, we combine human-centred design, AI capability and full-stack development to deliver products that feel effortless." },
      process: [
        { label: "Product strategy", title: "Define", body: "Outcomes, users, scope and commercial model." },
        { label: "UX & prototyping", title: "Design", body: "Human-centred design, validated before we build." },
        { label: "Engineering", title: "Build", body: "Full-stack development, tested and production-ready." },
        { label: "Support & optimise", title: "Operate", body: "Ongoing managed operations and continuous improvement." },
      ],
      closing: { heading: "Build the platform your organisation needs next.", body: "Tell us about your idea, product or workflow. We'll tell you what's worth building and what to do first.", cta: "Start a platform conversation →" },
    },
    {
      slug: "ai-services",
      number: "02",
      name: "AI Services",
      short: "From readiness and governance to private AI, agents, automation and managed AI operations.",
      intro: "An AI system embedded in real operations: secure, governed and working alongside people.",
      prompts: ["Show the board what AI could really do?", "A manual process your team keeps repeating?", "Moving from public AI tools to a managed program?", "Understand AI risk before going further?"],
      groups: [
        { title: "AI Advisory & Readiness", summary: "Map your position, real opportunities and risk, and build a practical roadmap before you commit to an AI program.", items: ["AI readiness assessments", "AI opportunity mapping", "Workflow and role analysis", "AI risk reviews", "Vendor, model and tool assessment", "Executive & board briefings"] },
        { title: "AI Governance & Policy", summary: "Adopt AI responsibly with the frameworks, policies and controls to use it safely and consistently.", items: ["AI policy development", "AI governance frameworks", "AI usage audits", "Compliance and risk controls", "Workforce training", "Adoption planning"] },
        { title: "AI Deployment", summary: "From proof of concept to production. We deploy private AI environments, agents, RAG systems and AI-enabled workflows, and run them.", items: ["Private AI environments", "AI agents & assistants", "RAG / knowledge systems", "Workflow integration", "AI governance controls", "Managed AI operations"] },
        { title: "AI Agents & Automation", summary: "Automate the repetitive, amplify the valuable. Agentic workflows, digital workers and process automation that run in production, not just in demos.", items: ["AI agents & agentic workflows", "Digital workers", "Process & workflow automation", "Human-in-the-loop design", "Automation governance"] },
      ],
      highlight: {
        eyebrow: "Productised offer",
        title: "AI Readiness Program",
        body: "An 8-week engagement designed to move your organisation from AI confusion to clear execution. Fixed price. Clear scope. Defined outcomes.",
        items: ["Executive AI workshop", "Workflow and systems audit", "AI opportunity mapping", "Use-case prioritisation", "Pilot planning", "AI governance and policy framework", "Implementation roadmap"],
        note: "Contact us for a tailored price",
      },
      process: [
        { label: "AI strategy", title: "Understand", body: "AI readiness assessment, opportunity mapping and governance framework." },
        { label: "Design & plan", title: "Architect", body: "AI system design, agent architecture and human-centred UX planning." },
        { label: "Build & deploy", title: "Engineer", body: "AI app development, agent engineering, integration and production deployment." },
        { label: "Manage & optimise", title: "Operate", body: "Ongoing AI support, performance monitoring, iteration and continuous improvement." },
      ],
      closing: { heading: "Make AI operational, not experimental.", body: "Tell us where you are with AI. We'll tell you what to do next.", cta: "Start an AI conversation →" },
    },
    {
      slug: "robotics",
      number: "03",
      name: "Robotics",
      short: "AI-enabled physical systems assessed, piloted and deployed safely into real operating environments.",
      intro: "AI-enabled physical systems, assessed and deployed safely into real operating environments, including the assistive robots behind Nashmi.",
      prompts: ["Test a robotics use case before full deployment?", "Unsure which platform fits your environment?", "Need to map safety, compliance and integration first?"],
      groups: [
        { title: "What we do", summary: "From curiosity to live operations.", items: ["Robotics readiness assessments", "Use-case identification and prioritisation", "Platform and vendor selection", "Pilot programs", "Humanoid robot deployment", "Quadruped robot deployment", "Wheeled robot deployment", "AI integration", "Sensor and environment integration", "Safety and compliance frameworks", "Operator training", "Managed robotics support"] },
        { title: "Humanoid", summary: "Built for human environments. Suited to reception, assistance, inspection and customer-facing roles.", items: [] },
        { title: "Quadruped", summary: "Built for complex terrain. Ideal for infrastructure monitoring, site inspection and remote assessment.", items: [] },
        { title: "Wheeled", summary: "Built for structured environments. Suited to guidance, delivery, logistics and repetitive movement tasks.", items: [] },
        { title: "Use cases", summary: "Practical applications in business, government and care today.", items: ["Assistive robots for people with disabilities", "Accessible classrooms and learning support", "Health facility support and logistics", "Facility security and patrol", "Infrastructure and site inspection", "Reception and wayfinding", "Internal logistics and delivery", "Remote site monitoring", "Data centre inspection", "Dangerous environment assessment"] },
      ],
      highlight: { eyebrow: "Featured offer", title: "Robotics Opportunity Assessment", body: "A short, structured engagement to identify where robotics could create value before you commit to deployment.", items: ["Environment review", "Use-case mapping", "Platform shortlist", "Risk and compliance overview", "Recommended next steps"] },
      process: [
        { label: "01", title: "Readiness & Discovery", body: "Environment, safety requirements, use cases and integration landscape." },
        { label: "02", title: "Platform Selection", body: "Assess humanoid, quadruped and wheeled options against your specific requirements." },
        { label: "03", title: "Pilot Program", body: "Deploy in a controlled environment. Measure outcomes. Build the case for broader rollout." },
        { label: "04", title: "Integration & AI", body: "Connect robots to systems, sensors and operational workflows." },
        { label: "05", title: "Deploy & Train", body: "Full deployment with operator training and safety frameworks in place." },
        { label: "06", title: "Ongoing Management", body: "Performance monitoring, support and expanding capability over time." },
      ],
      closing: { heading: "The organisations starting now will have the lead.", body: "Robotics readiness, use-case identification or a pilot program scoped and ready to run: start the conversation.", cta: "Start a robotics conversation →" },
    },
    {
      slug: "advisory",
      number: "04",
      name: "Advisory",
      short: "Technology, AI and platform decisions clarified before you invest, build or deploy.",
      intro: "Clarifying major technology decisions before you invest, build or deploy.",
      prompts: ["Need a roadmap that's practical, not theoretical?", "Unsure which platform, vendor or approach fits?", "Building the business case for a tech investment?", "Need an independent view before a major commitment?"],
      groups: [
        { title: "What we cover", summary: "Strategic technology partner. Not just a delivery team.", items: ["Technology audits", "AI readiness & opportunity assessments", "Digital strategy", "Product strategy", "Solution architecture", "Technology roadmaps", "Governance frameworks", "Vendor and platform assessment", "Transformation planning", "Executive advisory", "Board-level briefings", "Feasibility assessments", "Business case support"] },
      ],
      highlight: {
        eyebrow: "Ongoing engagement",
        title: "AI Advisory & Execution Partner",
        body: "We stay with you beyond strategy, helping your team execute, refine and scale AI across the business. Ongoing support. Strategic partnership. Real execution.",
        items: ["AI roadmap execution", "Tool and vendor selection", "Pilot delivery support", "Leadership guidance", "Ongoing optimisation"],
        note: "Retainer · contact us for a tailored price",
      },
      process: [],
      closing: { heading: "The right decision made early saves more than time.", body: "Tell us what you are trying to decide. We will tell you what we know, and what we would do.", cta: "Start an advisory conversation →" },
    },
    {
      slug: "48-hour-prototype",
      number: "★",
      name: "48 Hour Prototype",
      short: "Prove an AI or platform idea in two business days, before you commit budget.",
      intro: "A focused two-day engagement that turns a concept into something real: enough to show stakeholders, gather feedback and build momentum before a larger investment.",
      prompts: ["An idea, but unsure it's worth building?", "Need to show stakeholders before budget approval?", "Want to test an AI workflow before a full build?", "Need something tangible for a board discussion?"],
      groups: [
        { title: "What it can include", items: ["Clickable product prototype", "AI workflow demo", "Internal tool mock-up", "SaaS or MVP concept", "Automation flow", "Dashboard concept", "Customer portal prototype", "Robotics or AI use-case storyboard", "Technical feasibility notes", "Recommended next steps"] },
        { title: "Before → After", summary: "From abstract to tangible. From talk to traction.", items: ["Idea is abstract → Tangible prototype", "Hard to explain → Shared understanding", "Slow to approve → Faster decision-making", "Stakeholders disengaged → Stakeholders aligned", "Business case ambiguous → Clearer business case", "Build estimates inflated → Reduced build risk"] },
        { title: "When to use it", summary: "Win buy-in. Test an idea. Reduce uncertainty.", items: ["Internal tool sign-off before development", "Testing an AI workflow with a small team", "Securing budget for a new platform", "Showing the board what an AI initiative could look like", "Validating a product concept with customers", "Visualising a robotics or automation use case"] },
      ],
      process: [
        { label: "Day 1", title: "Briefing and discovery", body: "We understand the idea, the audience and what success looks like. We design the core concept and agree on deliverables." },
        { label: "Day 2", title: "Build and deliver", body: "We produce the prototype. You receive a working, shareable prototype and a short briefing on recommended next steps." },
      ],
      closing: { heading: "Ready to test an idea?", body: "Tell us what you're trying to build, test or prove. We'll turn it into something tangible in 48 hours.", cta: "Prototype your idea →" },
    },
  ] as Capability[],
  offers: [
    { title: "48 Hour Prototype", body: "Turn an idea into something tangible in two business days.", href: "/services/48-hour-prototype" },
    { title: "AI Readiness Audit", body: "Understand where you stand before committing to an AI program.", href: "/services/ai-services" },
    { title: "Technology Roadmap Sprint", body: "Create a practical roadmap in days, not months.", href: "/services/advisory" },
    { title: "Robotics Opportunity Assessment", body: "Identify the right robotics use cases for your environment.", href: "/services/robotics" },
    { title: "Platform Feasibility Review", body: "Validate your platform idea before building it.", href: "/services/platform-development" },
    { title: "AI Governance Framework", body: "Adopt AI responsibly. Build the controls your organisation needs.", href: "/services/ai-services" },
  ],
  industries: [
    { name: "Government & Public Sector", body: "Government is in our roots. We understand the security, compliance, procurement and operational requirements that shape public-sector delivery.", tags: ["Security", "Compliance", "AI Services", "Robotics", "Advisory"] },
    { name: "Education & Inclusion", body: "Accessible classrooms, assistive robotics and learning platforms that include every student. Home of Nashmi.", tags: ["Nashmi", "Accessibility", "AI", "Robotics"] },
    { name: "Health & Community", body: "Human-centred technology matters in environments where people, workflows and trust are critical.", tags: ["Human-Centred", "AI", "Robotics", "Platforms"] },
    { name: "Enterprise & Corporate", body: "From AI transformation to platform modernisation, we move complex organisations from strategy to operational capability.", tags: ["AI Services", "Platforms", "Advisory", "Managed Operations"] },
    { name: "Financial Services", body: "Regulated environments need technology that's secure, auditable and governed. Our AI, platform and advisory work is built for that reality.", tags: ["AI Governance", "Risk", "Compliance", "Platforms"] },
    { name: "Startups & Scaleups", body: "From MVP to managed platform. We help founders and growth teams validate, build and scale production-grade technology.", tags: ["MVP", "48 Hour Prototype", "SaaS", "AI"] },
  ],
  insights: [
    {
      topic: "Education",
      title: "Every child in the room: how robots can make inclusive classrooms work.",
      excerpt: "Inclusion fails when one teacher has to adapt every lesson five ways. Here's how a patient robot partner changes that, and what it must never do.",
      readTime: "7 min read",
      featured: true,
    },
    { topic: "Accessibility", title: "Designing robots with people with disabilities, not just for them." },
    { topic: "Education", title: "Telepresence: keeping homebound and hospitalised students in class." },
    { topic: "Accessibility", title: "Arabic-first assistive technology: why language is accessibility." },
    { topic: "Robotics", title: "Choosing between humanoid, quadruped and wheeled robots for your environment." },
    { topic: "Education", title: "Sign language robots: what Deaf educators taught us." },
    { topic: "AI Governance", title: "Why AI governance is the most important conversation your board is not having." },
    { topic: "Robotics", title: "Robots in the workplace: what leaders need to know before piloting." },
    { topic: "Human-centred", title: "Human-centred AI: why the best programs start with people, not technology." },
    { topic: "AI Governance", title: "Privacy for the most vulnerable users: our data principles for Nashmi." },
  ] as Insight[],
} ;

export type Content = typeof en;
